services:
  - type: web
    name: supa-chatbot-backend
    env: node
    plan: free
    buildCommand: pnpm install
    startCommand: pnpm start
    rootDir: bot
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: BOT_ENABLED
        value: "true"
      - key: ADMIN_SECRET_KEY
        generateValue: true
